theme = "tokyonight"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
[editor] 
auto-save = true
mouse = true
[editor.lsp]
display-inlay-hints=true
display-messages=true
